/**
 * Scorer Agent
 * 
 * An agent that determines the final score of the Requirement Analysis processing the scoring distillation JSON(generated by the Scoring Distiller Agent)
 * and produces a final score with rationale and feedback.
 */

import { Agent } from '@mastra/core/agent';
import { APIErrorProcessor, createModel } from '../../../utils';
import { SCORER_AGENT_INSTRUCTIONS, ScorerSchema } from './instructions';

// Model configuration - override via SCORER_LLM_MODEL_NAME env var
const DEFAULT_MODEL = 'qwen3.5:9b';
const MODEL_ID = process.env.SCORER_LLM_MODEL_NAME || DEFAULT_MODEL;
const PROVIDER_NAME = process.env.LLM_PROVIDER_NAME || 'TC-Ollama';

export const scorerAgent = new Agent({
    id: 'scorer-agent',
    name: 'Scorer',
    description: 'Determines the final score of the Requirement Analysis processing the scoring distillation JSON, and produces a final score with rationale and feedback.',
    instructions: SCORER_AGENT_INSTRUCTIONS,
    // Model with extended context and timeout-friendly settings
    // Override model via SCORER_LLM_MODEL_NAME env var (see recommendations above)
    model: createModel(PROVIDER_NAME, MODEL_ID),
    defaultOptions: {
        activeTools: [],
        maxSteps: 1,
        structuredOutput: {
            schema: ScorerSchema,
            // jsonPromptInjection: true,
        },
    },
    // Error processors handle API failures with retry
    errorProcessors: [
        new APIErrorProcessor({
            maxRetries: 2,
            retryablePatterns: [
                'timeout',
                'ETIMEDOUT',
                'ECONNRESET',
                'ECONNREFUSED',
                'socket hang up',
                '503',
                '502',
                '504',
                'rate limit',
                'overloaded',
                /context.*length.*exceeded/i,
                /model.*busy/i,
            ],
        }),
    ],
});
