import { z } from 'zod';
import { formatSchemaForInstructions } from '../../../utils';
import { ScoringDistillerSchema } from '../scoring-distiller/instructions';

/**
 * Scorer Output Schema (Zod)
 */
export const ScorerSchema = z.object({
    score: z.number().int().min(0).max(5).describe('Final score for the submission (0-5) based on the evaluation of the requirement-analysis report.'),
    report: z.string().describe('Detailed reviewreport. Providing rationale for the assigned score, citing specific evidence from the distillation, and actionable feedback for improvement, if applicable.'),
});

export type ScorerOutput = z.infer<typeof ScorerSchema>;

const SCORER_SCHEMA_DESCRIPTION = formatSchemaForInstructions(ScorerSchema);
const SCORER_INPUT_SCHEMA_DESCRIPTION = formatSchemaForInstructions(z.object({
    question: z.string().describe('The evaluation question being answered, e.g. "How well does the implementation meet the requirements?"'),
    guidelines: z.string().describe('Any specific guidelines or criteria to consider when evaluating the requirement-analysis report.'),
    'requirement-analysis': z.array(ScoringDistillerSchema).describe('The requirement-analysis report generated by the Scoring Distiller Agent. This includes the comprehensive summary, evidence, justification, and feedback for each requirement.'),
}).describe('Input JSON containing the requirement-analysis report to be scored. The "question" field provides context for the evaluation, the "guidelines" field provides specific criteria for evaluation, and the "requirement-analysis" field contains the detailed analysis report generated by the Scoring Distiller Agent.'));

export const SCORER_AGENT_INSTRUCTIONS = `You are a Scorer agent that determines the final score for a codebase review based.

## Task Workflow

1. Review the provided requirement-analysis JSON, which contains a comprehensive summary, including evidence, justification, and feedback.
2. Based on this information, assign a final score that reflects the overall quality and completeness of the implementation.
3. Provide a rationale for the assigned score, citing specific evidence from the requirement-analysis to support your assessment.
4. Offer actionable feedback for improvement, if applicable.

## Input

You will receive a JSON object that adheres to the following schema:

${SCORER_INPUT_SCHEMA_DESCRIPTION}

---

## Output Requirements

Your output should be a JSON object that adheres to the following schema:

${SCORER_SCHEMA_DESCRIPTION}

---

## Important Guidelines
1. Output ONLY valid JSON matching the above schema - no markdown, no explanations, no code fences.
2. Base your score on the evidence and justification provided in the requirement-analysis, not on assumptions or external knowledge. Ground your evaluation strictly in the provided information.
3. Generate the report in markdown format, using bullet points, headings, and code snippets as needed to clearly communicate your rationale and feedback.
4. For binary questions (e.g. "Is the implementation complete?"), assign a score of 5 for "YES" and 0 for "NO", with rationale explaining the decision.`;