import { createStep, createWorkflow } from "@mastra/core/workflows";
import z from "zod";
import pLimit from "p-limit";
import { tcAILogger } from "../../utils";
import { ScorerSchema, type ScorerOutput } from "../agents/scorer/instructions";
import { ScoringDistillerSchema } from "../agents/scoring-distiller/instructions";

// Configuration
const DEFAULT_TIMEOUT_MS = 10 * 60 * 1000; // 10 minutes default
const SCORER_TIMEOUT_MS = parseInt(process.env.SCORER_TIMEOUT_MS || '', 10) || DEFAULT_TIMEOUT_MS;
const MAX_RETRIES = 1;
const MAX_CONCURRENT_SCORERS = parseInt(process.env.MAX_CONCURRENT_SCORERS || '', 10) || 2;

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------

const scorerWorkflowInputSchema = z.object({
    aiWorkflowPath: z.string().describe('Absolute path to the AI workflow JSON file'),
    requirementAnalysis: z.array(ScoringDistillerSchema).describe('The requirement-analysis report generated by the Scoring Distiller Agent'),
});

/**
 * Token usage schema matching Mastra/AI SDK LanguageModelUsage type.
 */
const tokenUsageSchema = z.object({
    inputTokens: z.number().describe('Number of tokens in the prompt/input'),
    outputTokens: z.number().describe('Number of tokens in the completion/output'),
    totalTokens: z.number().describe('Total tokens used (inputTokens + outputTokens)'),
    cachedInputTokens: z.number().optional().describe('Number of input tokens read from cache'),
    cacheCreationInputTokens: z.number().optional().describe('Number of input tokens written to cache'),
    reasoningTokens: z.number().optional().describe('Number of tokens used for reasoning (chain-of-thought)'),
});

/**
 * Tool call record schema matching Mastra/AI SDK ToolCallPayload type.
 */
const toolCallRecordSchema = z.object({
    toolCallId: z.string().describe('Unique identifier for the tool call'),
    toolName: z.string().describe('Name of the tool that was called'),
    args: z.record(z.string(), z.unknown()).optional().describe('Arguments passed to the tool'),
    durationMs: z.number().optional().describe('Execution duration in milliseconds'),
    success: z.boolean().optional().describe('Whether the tool call succeeded'),
    error: z.string().optional().describe('Error message if the tool call failed'),
});

/**
 * Aggregated tool usage statistics for an analysis run.
 */
const toolUsageSchema = z.object({
    totalCalls: z.number().describe('Total number of tool calls made'),
    uniqueTools: z.array(z.string()).describe('List of unique tool names used'),
    callsByTool: z.record(z.string(), z.number()).describe('Number of calls per tool name'),
    totalDurationMs: z.number().optional().describe('Total time spent in tool executions'),
    successCount: z.number().describe('Number of successful tool calls'),
    errorCount: z.number().describe('Number of failed tool calls'),
    calls: z.array(toolCallRecordSchema).optional().describe('Detailed log of each tool call'),
});

/**
 * Question score result schema
 */
const questionScoreResultSchema = z.object({
    questionId: z.string().describe('Scorecard question ID'),
    questionDescription: z.string().describe('Question description/text'),
    questionType: z.enum(['SCALE', 'YES_NO', 'TEST_CASE']).describe('Question type'),
    weight: z.number().describe('Question weight'),
    scorer: ScorerSchema.describe('Scorer agent output'),
    tokenUsage: tokenUsageSchema.optional().describe('Token usage for this question scoring'),
    toolUsage: toolUsageSchema.optional().describe('Tool usage statistics for this question'),
    durationMs: z.number().optional().describe('Duration of scoring in milliseconds'),
    retryCount: z.number().optional().describe('Number of retries needed'),
    error: z.string().optional().describe('Error message if scoring failed'),
});

/**
 * Section score result schema
 */
const sectionScoreResultSchema = z.object({
    sectionId: z.string().describe('Scorecard section ID'),
    sectionName: z.string().describe('Section name'),
    weight: z.number().describe('Section weight'),
    questions: z.array(questionScoreResultSchema).describe('Question results in this section'),
});

/**
 * Group score result schema
 */
const groupScoreResultSchema = z.object({
    groupId: z.string().describe('Scorecard group ID'),
    groupName: z.string().describe('Group name'),
    weight: z.number().describe('Group weight'),
    sections: z.array(sectionScoreResultSchema).describe('Section results in this group'),
});

/**
 * Scorer workflow output schema
 */
const scorerWorkflowOutputSchema = z.object({
    scorecard: z.array(groupScoreResultSchema).describe('Full scorecard results organized by groups, sections, and questions'),
    totalUsage: tokenUsageSchema.describe('Aggregated token usage across all question scorings'),
    toolUsage: toolUsageSchema.describe('Aggregated tool usage across all question scorings'),
    summary: z.object({
        totalQuestions: z.number().describe('Total number of questions scored'),
        successCount: z.number().describe('Number of successfully scored questions'),
        errorCount: z.number().describe('Number of failed question scorings'),
        totalDurationMs: z.number().describe('Total duration of all scorings'),
    }).describe('Summary statistics'),
});

type TokenUsage = z.infer<typeof tokenUsageSchema>;
type ToolUsage = z.infer<typeof toolUsageSchema>;
type ToolCallRecord = z.infer<typeof toolCallRecordSchema>;
type QuestionScoreResult = z.infer<typeof questionScoreResultSchema>;

// ---------------------------------------------------------------------------
// Helper Functions
// ---------------------------------------------------------------------------

/**
 * Executes agent.generate with timeout and abort support.
 */
async function executeWithTimeout<T>(
    operation: (signal: AbortSignal) => Promise<T>,
    timeoutMs: number,
    label: string,
): Promise<T> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => {
        controller.abort();
        tcAILogger.warn(`[scorer-workflow] ${label} - Timeout after ${timeoutMs}ms`);
    }, timeoutMs);

    try {
        const result = await operation(controller.signal);
        return result;
    } finally {
        clearTimeout(timeoutId);
    }
}

/**
 * Combines token usage from two sources.
 */
function combineTokenUsage(a?: TokenUsage, b?: TokenUsage): TokenUsage {
    return {
        inputTokens: (a?.inputTokens ?? 0) + (b?.inputTokens ?? 0),
        outputTokens: (a?.outputTokens ?? 0) + (b?.outputTokens ?? 0),
        totalTokens: (a?.totalTokens ?? 0) + (b?.totalTokens ?? 0),
        cachedInputTokens: (a?.cachedInputTokens ?? 0) + (b?.cachedInputTokens ?? 0) || undefined,
        cacheCreationInputTokens: (a?.cacheCreationInputTokens ?? 0) + (b?.cacheCreationInputTokens ?? 0) || undefined,
        reasoningTokens: (a?.reasoningTokens ?? 0) + (b?.reasoningTokens ?? 0) || undefined,
    };
}

/**
 * Combines tool usage from two sources.
 */
function combineToolUsage(a?: ToolUsage, b?: ToolUsage): ToolUsage {
    const callsByTool: Record<string, number> = { ...(a?.callsByTool ?? {}) };
    for (const [tool, count] of Object.entries(b?.callsByTool ?? {})) {
        callsByTool[tool] = (callsByTool[tool] ?? 0) + count;
    }

    const allCalls: ToolCallRecord[] = [...(a?.calls ?? []), ...(b?.calls ?? [])];

    return {
        totalCalls: (a?.totalCalls ?? 0) + (b?.totalCalls ?? 0),
        uniqueTools: [...new Set([...(a?.uniqueTools ?? []), ...(b?.uniqueTools ?? [])])],
        callsByTool,
        totalDurationMs: ((a?.totalDurationMs ?? 0) + (b?.totalDurationMs ?? 0)) || undefined,
        successCount: (a?.successCount ?? 0) + (b?.successCount ?? 0),
        errorCount: (a?.errorCount ?? 0) + (b?.errorCount ?? 0),
        calls: allCalls.length > 0 ? allCalls : undefined,
    };
}

/** Agent generate result type */
interface AgentGenerateResult {
    object?: ScorerOutput;
    text?: string;
    totalUsage?: {
        inputTokens?: number;
        outputTokens?: number;
        totalTokens?: number;
        cachedInputTokens?: number;
        cacheCreationInputTokens?: number;
        reasoningTokens?: number;
    };
    finishReason?: string;
    toolCalls?: unknown[];
    toolResults?: unknown[];
    error?: { message: string };
}

/**
 * Builds the prompt for the scorer agent following SCORER_INPUT_SCHEMA_DESCRIPTION format.
 */
function buildScorerPrompt(
    question: string,
    guidelines: string,
    requirementAnalysis: z.infer<typeof ScoringDistillerSchema>[],
): string {
    const input = {
        question,
        guidelines,
        'requirement-analysis': requirementAnalysis,
    };
    return JSON.stringify(input);
}

/**
 * Scores a single question with retry logic and timeout handling.
 */
async function scoreQuestion(
    scorerAgent: { generate: (prompt: string, options?: unknown) => Promise<unknown> },
    question: {
        id: string;
        description: string;
        guidelines: string;
        type: 'SCALE' | 'YES_NO' | 'TEST_CASE';
        weight: number;
    },
    requirementAnalysis: z.infer<typeof ScoringDistillerSchema>[],
    logPrefix: string,
): Promise<QuestionScoreResult> {
    let retryCount = 0;
    let lastError: Error | null = null;

    while (retryCount <= MAX_RETRIES) {
        const startTime = Date.now();
        const attemptLabel = retryCount > 0 ? ` (retry ${retryCount}/${MAX_RETRIES})` : '';

        tcAILogger.info(`${logPrefix} Starting scoring${attemptLabel}`);

        try {
            const prompt = buildScorerPrompt(question.description, question.guidelines, requirementAnalysis);

            const rawResult = await executeWithTimeout(
                async (_signal) => scorerAgent.generate(prompt),
                SCORER_TIMEOUT_MS,
                `${logPrefix} Scorer execution`,
            );

            const result = rawResult as AgentGenerateResult;
            const durationMs = Date.now() - startTime;

            const tokenUsage: TokenUsage = {
                inputTokens: result.totalUsage?.inputTokens ?? 0,
                outputTokens: result.totalUsage?.outputTokens ?? 0,
                totalTokens: result.totalUsage?.totalTokens ?? 0,
                cachedInputTokens: result.totalUsage?.cachedInputTokens,
                cacheCreationInputTokens: result.totalUsage?.cacheCreationInputTokens,
                reasoningTokens: result.totalUsage?.reasoningTokens,
            };

            // Tool usage (scorer agent typically has no tools, but track anyway)
            const toolUsage: ToolUsage = {
                totalCalls: 0,
                uniqueTools: [],
                callsByTool: {},
                successCount: 0,
                errorCount: 0,
            };

            if (result.error) {
                throw new Error(result.error.message);
            }

            // Check for structured output
            let scorerOutput: ScorerOutput;
            if (result.object) {
                scorerOutput = result.object;
            } else if (result.text) {
                try {
                    const parsed = JSON.parse(result.text);
                    scorerOutput = ScorerSchema.parse(parsed);
                } catch (parseError) {
                    throw new Error(`Failed to parse scorer output: ${parseError}`, { cause: parseError });
                }
            } else {
                throw new Error('No structured output or text returned from scorer agent');
            }

            tcAILogger.info(`${logPrefix} Scoring complete in ${durationMs}ms`);
            tcAILogger.info(`${logPrefix} Score: ${scorerOutput.score}/5, Tokens: input=${tokenUsage.inputTokens}, output=${tokenUsage.outputTokens}`);

            return {
                questionId: question.id,
                questionDescription: question.description,
                questionType: question.type,
                weight: question.weight,
                scorer: scorerOutput,
                tokenUsage,
                toolUsage,
                durationMs,
                retryCount,
            };
        } catch (error) {
            const durationMs = Date.now() - startTime;
            lastError = error instanceof Error ? error : new Error(String(error));
            const isTimeout = lastError.name === 'AbortError' || lastError.message.includes('abort');

            tcAILogger.error(`${logPrefix} Failed after ${durationMs}ms: ${lastError.message}`);

            if (retryCount < MAX_RETRIES) {
                retryCount++;
                const retryReason = isTimeout ? 'timeout' : 'error';
                tcAILogger.info(`${logPrefix} Retrying due to ${retryReason}`);
                continue;
            }

            // Max retries exhausted
            return {
                questionId: question.id,
                questionDescription: question.description,
                questionType: question.type,
                weight: question.weight,
                scorer: { score: 0, report: `Scoring failed: ${lastError.message}` },
                durationMs,
                retryCount,
                error: lastError.message,
            };
        }
    }

    // Should never reach here
    return {
        questionId: question.id,
        questionDescription: question.description,
        questionType: question.type,
        weight: question.weight,
        scorer: { score: 0, report: `Unexpected error: ${lastError?.message || 'Unknown'}` },
        retryCount,
        error: lastError?.message,
    };
}

// ---------------------------------------------------------------------------
// Workflow Steps
// ---------------------------------------------------------------------------

/**
 * Combined step that reads the AI workflow and processes the scorecard.
 * This step handles reading the aiWorkflow from the path and processing scorecard questions.
 */
const readAndProcessScorecard = createStep({
    id: 'read-and-process-scorecard',
    description: 'Reads the AI workflow JSON and iterates over scorecard groups, sections, and questions, prompting the scorer agent for each question.',
    inputSchema: scorerWorkflowInputSchema,
    outputSchema: scorerWorkflowOutputSchema,
    execute: async ({ mastra, inputData }) => {
        const { aiWorkflowPath, requirementAnalysis } = inputData;

        // Read AI workflow using the same logic as readAiWorkflow step
        tcAILogger.info(`[scorer-workflow] Reading AI workflow from: ${aiWorkflowPath}`);
        const { readFile } = await import('node:fs/promises');
        const content = await readFile(aiWorkflowPath, 'utf-8');
        const aiWorkflow = JSON.parse(content) as any;
        tcAILogger.info(`[scorer-workflow] AI workflow loaded successfully (${content.length} chars)`);

        // Get scorer agent
        const scorerAgent = mastra!.getAgentById('scorer-agent');
        if (!scorerAgent) {
            throw new Error('Scorer Agent not found in Mastra');
        }

        const scorecard = aiWorkflow.scorecard;
        const groups = scorecard.scorecardGroups;

        tcAILogger.info(`[scorer-workflow] === STARTING SCORECARD PROCESSING ===`);
        tcAILogger.info(`[scorer-workflow] LLM Configuration for Scorer Agent: ${JSON.stringify(scorerAgent.model, null, 2)}`);
        tcAILogger.info(`[scorer-workflow] Scorecard: ${scorecard.name} (v${scorecard.version})`);
        tcAILogger.info(`[scorer-workflow] Groups: ${groups.length}`);
        tcAILogger.info(`[scorer-workflow] Requirement Analysis Items: ${requirementAnalysis.length}`);
        tcAILogger.info(`[scorer-workflow] Scorer Timeout: ${SCORER_TIMEOUT_MS}ms, Max Retries: ${MAX_RETRIES}, Concurrency: ${MAX_CONCURRENT_SCORERS}`);

        // Dump the requirements JSON analysis sent to the model
        tcAILogger.info(`[scorer-workflow] ========== REQUIREMENTS JSON ANALYSIS INPUT ==========`);
        tcAILogger.info(`[scorer-workflow] ${JSON.stringify(requirementAnalysis, null, 2)}`);
        tcAILogger.info(`[scorer-workflow] ======================================================`);

        // Count total questions
        let totalQuestions = 0;
        for (const group of groups) {
            for (const section of group.sections) {
                totalQuestions += section.questions.length;
            }
        }
        tcAILogger.info(`[scorer-workflow] Total Questions: ${totalQuestions}`);

        // Initialize aggregation
        let totalUsage: TokenUsage = { inputTokens: 0, outputTokens: 0, totalTokens: 0 };
        let totalToolUsage: ToolUsage = {
            totalCalls: 0,
            uniqueTools: [],
            callsByTool: {},
            successCount: 0,
            errorCount: 0,
        };
        let successCount = 0;
        let errorCount = 0;
        let totalDurationMs = 0;

        // ---------------------------------------------------------------------------
        // Phase 1: Flatten all questions from all groups/sections for batch processing
        // ---------------------------------------------------------------------------
        interface QuestionWithContext {
            groupId: string;
            groupName: string;
            groupWeight: number;
            sectionId: string;
            sectionName: string;
            sectionWeight: number;
            question: {
                id: string;
                description: string;
                guidelines: string;
                type: 'SCALE' | 'YES_NO' | 'TEST_CASE';
                weight: number;
            };
            globalIndex: number;
        }

        const allQuestions: QuestionWithContext[] = [];
        let globalIndex = 0;

        for (const group of groups) {
            for (const section of group.sections) {
                const questions = section.questions as QuestionWithContext['question'][];
                for (const question of questions) {
                    allQuestions.push({
                        groupId: group.id,
                        groupName: group.name,
                        groupWeight: group.weight,
                        sectionId: section.id,
                        sectionName: section.name,
                        sectionWeight: section.weight,
                        question,
                        globalIndex: globalIndex++,
                    });
                }
            }
        }

        tcAILogger.info(`[scorer-workflow] Collected ${allQuestions.length} questions across ${groups.length} groups`);
        tcAILogger.info(`[scorer-workflow] Concurrency limit: ${MAX_CONCURRENT_SCORERS}`);

        // ---------------------------------------------------------------------------
        // Phase 2: Process all questions using streaming worker pool
        // ---------------------------------------------------------------------------
        const allResults = new Map<string, QuestionScoreResult>();
        const limit = pLimit(MAX_CONCURRENT_SCORERS);
        let completedCount = 0;

        const scoringPromises = allQuestions.map((item) =>
            limit(async () => {
                const currentIndex = item.globalIndex + 1;
                const logPrefix = `[scorer-workflow] [${currentIndex}/${totalQuestions}] [${item.question.id}]`;

                const result = await scoreQuestion(
                    scorerAgent,
                    {
                        id: item.question.id,
                        description: item.question.description,
                        guidelines: item.question.guidelines,
                        type: item.question.type,
                        weight: item.question.weight,
                    },
                    requirementAnalysis,
                    logPrefix,
                );

                completedCount++;
                tcAILogger.info(`[scorer-workflow] Progress: ${completedCount}/${totalQuestions} completed`);

                return { questionId: item.question.id, result };
            })
        );

        const allBatchResults = await Promise.all(scoringPromises);

        // Store results and aggregate stats
        for (const { questionId, result } of allBatchResults) {
            allResults.set(questionId, result);

            if (result.tokenUsage) {
                totalUsage = combineTokenUsage(totalUsage, result.tokenUsage);
            }
            if (result.toolUsage) {
                totalToolUsage = combineToolUsage(totalToolUsage, result.toolUsage);
            }
            if (result.durationMs) {
                totalDurationMs += result.durationMs;
            }
            if (result.error) {
                errorCount++;
            } else {
                successCount++;
            }
        }

        // ---------------------------------------------------------------------------
        // Phase 3: Reassemble results into group/section structure
        // ---------------------------------------------------------------------------
        const scorecardResults: z.infer<typeof groupScoreResultSchema>[] = [];

        for (const group of groups) {
            const sectionResults: z.infer<typeof sectionScoreResultSchema>[] = [];

            for (const section of group.sections) {
                const questions = section.questions as { id: string }[];
                const questionResults: QuestionScoreResult[] = questions.map(q => {
                    const result = allResults.get(q.id);
                    if (!result) {
                        throw new Error(`Missing result for question ${q.id}`);
                    }
                    return result;
                });

                sectionResults.push({
                    sectionId: section.id,
                    sectionName: section.name,
                    weight: section.weight,
                    questions: questionResults,
                });
            }

            scorecardResults.push({
                groupId: group.id,
                groupName: group.name,
                weight: group.weight,
                sections: sectionResults,
            });
        }

        // Log summary
        tcAILogger.info(`[scorer-workflow] === SCORECARD PROCESSING COMPLETE ===`);
        tcAILogger.info(`[scorer-workflow] Questions Processed: ${totalQuestions}`);
        tcAILogger.info(`[scorer-workflow] Success: ${successCount}, Errors: ${errorCount}`);
        tcAILogger.info(`[scorer-workflow] Total Tokens: input=${totalUsage.inputTokens}, output=${totalUsage.outputTokens}, total=${totalUsage.totalTokens}`);
        tcAILogger.info(`[scorer-workflow] Total Duration: ${totalDurationMs}ms (${(totalDurationMs / 1000).toFixed(1)}s)`);
        tcAILogger.info(`[scorer-workflow] Avg Duration per Question: ${totalQuestions > 0 ? (totalDurationMs / totalQuestions).toFixed(0) : 0}ms`);

        return {
            scorecard: scorecardResults,
            totalUsage,
            toolUsage: totalToolUsage,
            summary: {
                totalQuestions,
                successCount,
                errorCount,
                totalDurationMs,
            },
        };
    },
});

// ---------------------------------------------------------------------------
// Workflow Definition
// ---------------------------------------------------------------------------

export const scorerWorkflow = createWorkflow({
    id: 'scorer-workflow',
    description: 'Reads the AI workflow scorecard and processes each question with the scorer agent, producing a full scorecard report.',
    inputSchema: scorerWorkflowInputSchema,
    outputSchema: scorerWorkflowOutputSchema,
})
    .then(readAndProcessScorecard);
